---
- hosts: app
  sudo: true
  sudo_user: gp2

  tasks:
  - name: Get git repo
    git: repo=https://github.com/flyingmachine/gratefulplace2.git
         dest=${project_root}/code/repo
         depth=10
         
  - name: Install npm deps
    shell: chdir=${project_root}/code/repo/html-app/ npm install && bower install

  - name: Install ruby deps
    shell: chdir=${project_root}/code/repo/html-app/ /usr/local/rbenv/versions/1.9.3-p385/bin/bundle