---
- hosts: app
  sudo: true
  sudo_user: gp2

  vars:
    - html_app: ${project_root}/code/repo/html-app
    - server_app: ${project_root}/code/repo/server

  tasks:
  - name: Get git repo
    git: repo=https://github.com/flyingmachine/gratefulplace2.git
         dest=${project_root}/code/repo
         depth=10
         
  - name: Install npm deps
    shell: chdir=${html_app} npm install && bower install

  - name: Install ruby deps
    shell: chdir=${html_app} bundle

  - name: build html app
    shell: chdir=${html_app} grunt build

  - name: move html app to server app
    shell: chdir=${server_app} cp -R ${html_app}/targets/public resources/html-app