---
- hosts: app
  sudo: true

  tasks:
  - name: Create the project directory.
    file: state=directory path=${project_root}

  - name: Create user.
    user: home=${project_root}/home/ name=${project_name} state=present

  - name: Update the project directory.
    file: group=${project_name} owner=${project_name} mode=755 state=directory path=${project_root}
    
  - name: Create the code directory.
    file: group=${project_name} owner=${project_name} mode=755 state=directory path=${project_root}/code/

  - name: Allow new package repos
    apt: pkg=python-software-properties state=installed update-cache=yes

  - name: Add nodejs repo
    apt_repository: repo=ppa:chris-lea/node.js

  - name: Install required system packages.
    apt: pkg=${item} state=installed update-cache=yes
    with_items: ${system_packages}

  - name: install grunt & bower
    shell: npm install -g grunt-cli bower

  - name: Change permissions.
    shell: chown -R ${project_name}:${project_name} ${project_root}

  - name: Get leiningen
    get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin/lein
    
  - name: Leiningen permissions
    shell: chmod +x /usr/local/bin/lein

  - name: install bundler
    shell: gem install bundler
    
  - name: Upload web app upstart config file
    copy: src=files/${project_name}-upstart.conf dest=/etc/init/${project_name}.conf

  - name: Make app log directory
    file: state=directory path=/var/log/${project_name}
    
  - name: Change app log permissions
    shell: chown -R ${project_name}:${project_name} /var/log/${project_name}
    
# - include: vendor/rbenv/main.yml
    
- hosts: database
  sudo: true

  tasks:
  - name: Create datomic user.
    user: name=datomic state=present

  - name: Create datomic data directory
    file: state=directory path=${datomic_data_dir}

  - name: Change data permissions
    shell: chown -R datomic:datomic ${datomic_data_dir}

  - name: Make datomic log directory
    file: state=directory path=/var/log/datomic
    
  - name: Change data permissions
    shell: chown -R datomic:datomic /var/log/datomic

  - name: Check datomic installation
    command: "ls ${datomic_dir}/${datomic_filename}"
    register: datomic_exists
    ignore_errors: true

  - name: Create datomic directory
    file: state=directory path=${datomic_dir}
    when: datomic_exists|failed

  - name: Download datomic
    get_url: url=http://downloads.datomic.com/${datomic_version}/${datomic_filename}.zip dest=${datomic_dir}
    when: datomic_exists|failed

  - name: Unpack datomic
    command: chdir=${datomic_dir} unzip ${datomic_filename}.zip
    when: datomic_exists|failed

  - name: Upload datomic properties file
    copy: src=files/datomic-transactor.properties dest=${datomic_dir}/transactor.properties
    when: datomic_exists|failed
    
  - name: Upload datomic upstart config file
    copy: src=files/datomic-upstart.conf dest=/etc/init/datomic.conf
    when: datomic_exists|failed
    
  - name: Link datomic
    command: ln -s ${datomic_dir}/${datomic_filename} ${datomic_dir}/runtime
    when: datomic_exists|failed

  - name: Change lib permissions
    shell: chown -R datomic:datomic ${datomic_dir}

  - name: ensure datomic is running
    service: name=datomic state=started

- include: deploy.yml

- hosts: app
  sudo: true

  tasks:
  - name: load database
    command: java -jar ${project_root}/code/gp2.jar db/reload